#Reproducibility homework R coding - a cleaner place to do the code before transfer to Rmd.

library(palmerpenguins)
library(ggplot2)
library(janitor)
library(dplyr)

head(penguins_raw) #raw penguins data

data.clean <- function(penguins_raw){ #Function for cleaning data
  penguins_raw %>%
    select(-starts_with("delta")) %>%
    select(-Comments) %>%
    clean_names()
}
penguins_clean <- data.clean(penguins_raw) #Create clean data
head(penguins_clean)

#Create a box plot of body mass between penguin species
mass_boxplot <- ggplot(data = penguins_clean, 
                          aes(x = species, 
                              y = body_mass_g)) +
  geom_boxplot(aes(color = species), show.legend = FALSE)

mass_boxplot #Show boxplot in intitial form. It's a poor plot.
#Full common and binomial names are given for both species.
#They white on grey theme looks ugly.
#y axis label looks autogenerated, because it is.
#Default colours include red and green, which is colourblind-unfriendly.
#The raw data could be included alongside the box plots.

mass_boxplot2 <- ggplot(data = penguins_clean, aes(x = species, y = body_mass_g, ylab = 'Mass (g)')) +
  geom_boxplot(aes(color = species), show.legend = FALSE) +
  geom_jitter(aes(color = species), alpha = 0.4, show.legend = FALSE, 
              position = position_jitter(width = 0.1, seed = 0)) +
  labs(y = "Mass (g)", x = "Species") +
  scale_color_manual(values = c("magenta","orange","blue")) +
  scale_x_discrete(labels=c("Adelie","Chinstrap","Gentoo")) +
  theme_bw()

mass_boxplot2


##Question 4 - run a statistical test on the dataset and produce a figure to explain it
#I'll do a linear regression comparing flipper length with culmen (bill) length in gentoos.
#First I need to filter out gentoo data, then plot the graph and perform the analysis.
penguins_clean

gentoo <- filter(penguins_clean, species == 'Gentoo penguin (Pygoscelis papua)')
gentoo #Filtered dataset

ggplot(data = gentoo,
       aes(x = flipper_length_mm,
           y = culmen_length_mm,
       )) +
  labs(y = "Culmen length (mm)", x = "Flipper length (mm)", title = "Flipper and culmen length in gentoo penguins") +
  geom_point(colour = 'blue') +
  geom_smooth(method='lm') 

gentoo_mod <- lm(formula = culmen_length_mm ~ flipper_length_mm, data = gentoo) #Linear regression
summary(gentoo_mod)

